---
- hosts: appserver
  become: true
  tasks:
     - name: Create tomcat directory
     #  command: mkdir /usr/local/tomcat
       file:
           path: /opt/tomcat
           state: directory
     - name: Download Tomcat
       get_url:
             url: https://mirrors.estointernet.in/apache/tomcat/tomcat-7/v7.0.104/bin/apache-tomcat-7.0.104.tar.gz
             dest: /opt/tomcat
     - name: Extract tomcat
       unarchive:
              src: /opt/tomcat/apache-tomcat-7.0.104.tar.gz
              dest: /opt/tomcat
              copy: no
    # - name: Create tomcat users
    #   copy: src=tomcat-users.xml dest=/opt/tomcat/apache-tomcat-7.0.100/conf
     - name: Deploy sample application
       copy: src=/var/lib/jenkins/workspace/devopsjuneNew/webapp/target/webapp.war dest=/opt/tomcat/apache-tomcat-7.0.104/webapps

     - name: start tomcat
       shell: nohup  /opt/tomcat/apache-tomcat-7.0.104/bin/catalina.sh start
       register: result

